### ISSUE TITLE
alembic upgrade head 升级数据库时报错

### ISSUE THREAD

**Issue by dongfengweixiao** [amisadmin/fastapi_user_auth#6]
新增任意表后，执行 `alembic revision --autogenerate -m "something" ` 生成脚本，执行 `alembic upgrade head` 时报错。

发生异常: ProgrammingError
(sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.InvalidTableDefinitionError'>: column "group_id" is in a primary key
[SQL: ALTER TABLE auth_group_roles ALTER COLUMN group_id DROP NOT NULL]
(Background on this error at: https://sqlalche.me/e/14/f405)

使用数据库为 pgsql，使用的驱动为 asyncpg。如需更多信息，请告知。

**Comment by amisadmin** [comment]
#7
