### ISSUE TITLE
使用 JwtTokenStore 时无法正常 logout

### ISSUE THREAD

**Issue by Sug2077** [amisadmin/fastapi_user_auth#8]
fastapi_user_auth\auth\backends\jwt.py
JwtTokenStore.destroy_token
问题大概出现在这里

**Comment by amisadmin** [comment]
是的, `Jwt`从原理上无法销毁token, 只能通过在前端销毁`cookie`方式模拟退出登录.这个问题有空完善一下.

**Comment by Sug2077** [comment]
> > fastapi_user_auth\auth\backends\jwt.py JwtTokenStore.destroy_token 问题大概出现在这里
> 
> 请教一下我用官方的domo使用token会出现这个错误！文件和函数可以正常访问，但是一运行就报这个错误： ![图像](https://user-images.githubusercontent.com/10046182/257823904-8ee0953a-bcd1-4154-bca4-70114140d91c.png)
缺少对应模块 pip install jose

**Comment by tracydzf** [comment]
> pip install jose

https://github.com/mpdavis/python-jose 应该是这个吧？

**Comment by Sug2077** [comment]
> > pip install jose
> 
> https://github.com/mpdavis/python-jose 应该是这个吧？

太久了  忘记了  你试试
