### ISSUE TITLE
页面问题

### ISSUE THREAD

**Issue by cuckoo0606** [amisadmin/fastapi_user_auth#9]
实际的 `Hero` 表
![image](https://user-images.githubusercontent.com/17846092/171027048-a030fab2-2f49-43ef-ac9a-e2398cd788d1.png)

页面显示异常
![image](https://user-images.githubusercontent.com/17846092/171027225-f6d43729-5700-4df0-8b42-7fd26b0cb00c.png)

创建英雄时, 如果先填写英雄名称, 则不能选择团队; 如果先选择团队, 再填写名称是可以的
![image](https://user-images.githubusercontent.com/17846092/171027347-2543b683-7369-45c3-9878-b5c1a6a42398.png)

**Comment by amisadmin** [comment]
感谢反馈，应该是关联模型数据导致的，你可以查看一下linkmodel数据库中的数据
